animation-force-steps = true;
animation-for-open-window = "zoom";
animations = true;

backend = "glx";

corner-radius = 12;

detect-transient = true;

fading = true;

blur-kern = "7x7box";
blur-background = true;

focus-exclude = ["class_g = 'Rofi'"];

inactive-opacity = 0.8;

vsync = true;
