#!/usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

killall picom; picom
killall polybar; zsh ~/.config/polybar/launch.sh --shades &
killall unclutter; unclutter &

nitrogen --restore

setxkbmap -layout us,ru

bspc config border_width        0
bspc config window_gap          12
