;; WM setitngs

[color]

background = #1F1F1F
foreground = #FFAAFF
foreground-alt = #8F8F8F

[bar/main]
padding-left = 15px
padding-right = 0px
bottom = false
fixed-center = true

width = 1896px
height = 36
offset-x = 12px
offset-y = 12px

background = ${color.background}
foreground = ${color.foreground}

underline-size = 2
underline-color = ${color.foreground}

padding = 0

module-margin-left = 3px
module-margin-right = 3px

font-0 = "JetBrains Mono:pixelsize=12;3"
font-1 = "Iosevka Nerd Font:pixelsize=14;4"

separator = 

modules-left = launcher workspaces
modules-center = xwindow
modules-right = alsa battery network xkeyboard date

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = "  %layout% "
label-layout-foreground = ${colors.foreground}

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/alsa]
type = internal/alsa

master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

master-mixer = Master

interval = 5

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.background}
format-volume-padding = 2

format-muted = <label-muted>
format-muted-prefix = 婢
format-muted-background = ${color.background}
format-muted-padding = 2

label-volume = %percentage%%

label-muted = " Muted"
label-muted-foreground = ${color.foreground}

ramp-volume-0 = 奄
ramp-volume-1 = 奔
ramp-volume-2 = 墳

ramp-headphones-0 = 

[module/battery]
type = internal/battery

full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC0

poll-interval = 5

time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-charging-background = ${color.background}
format-charging-padding = 2

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${color.background}
format-discharging-padding = 2

format-full = <label-full>
format-full-prefix = 
format-full-background = ${color.background}
format-full-padding = 2

label-charging = %percentage%%

label-discharging = %percentage%%

label-full = " Full"

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 

animation-charging-framerate = 750

[module/date]
type = internal/date

interval = 1.0

time = " %a, %d %b %Y    %H:%M"

format = <label>
format-background = ${color.background}
format-padding = 2

label = %time%

[module/network]
type = internal/network
interface = wlan0

interval = 1.0

accumulate-stats = true

unknown-as-up = true

format-connected = <ramp-signal> <label-connected>
format-connected-background = ${color.background}
format-connected-padding = 2

format-disconnected = <label-disconnected>
format-disconnected-prefix = 睊
format-disconnected-background = ${color.background}
format-disconnected-padding = 2

label-connected = "%{A1:networkmanager_dmenu &:}%essid%%{A}"

label-disconnected = "%{A1:networkmanager_dmenu &:} Offline%{A}"

ramp-signal-0 = 直
ramp-signal-1 = 直
ramp-signal-2 = 直


[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true

enable-click = true

enable-scroll = true

icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-default = 

format = <label-state>
format-padding = 1
format-background = ${color.background}

label-monitor = %name%

label-active = 
label-active-foreground = ${color.foreground}

label-occupied = 
label-occupied-foreground = ${color.foreground}

label-urgent = 
label-urgent-foreground = ${color.background}

label-empty = 

label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1

[module/launcher]
type = custom/text

content = 異

click-left = rofi -show drun
